# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projekt_informatyka_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjektInformatykaDialogBase(object):
    def setupUi(self, ProjektInformatykaDialogBase):
        ProjektInformatykaDialogBase.setObjectName("ProjektInformatykaDialogBase")
        ProjektInformatykaDialogBase.resize(588, 330)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        ProjektInformatykaDialogBase.setFont(font)
        self.button_box = QtWidgets.QDialogButtonBox(ProjektInformatykaDialogBase)
        self.button_box.setGeometry(QtCore.QRect(420, 290, 161, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(ProjektInformatykaDialogBase)
        self.label.setGeometry(QtCore.QRect(180, 30, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_answer = QtWidgets.QLabel(ProjektInformatykaDialogBase)
        self.label_answer.setGeometry(QtCore.QRect(20, 240, 571, 21))
        self.label_answer.setObjectName("label_answer")
        self.mMapLayerComboBox = QgsMapLayerComboBox(ProjektInformatykaDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(100, 80, 361, 27))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.pushButton_calculate_dh = QtWidgets.QPushButton(ProjektInformatykaDialogBase)
        self.pushButton_calculate_dh.setGeometry(QtCore.QRect(10, 120, 281, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.pushButton_calculate_dh.setFont(font)
        self.pushButton_calculate_dh.setObjectName("pushButton_calculate_dh")
        self.pushButton_calculate_area = QtWidgets.QPushButton(ProjektInformatykaDialogBase)
        self.pushButton_calculate_area.setGeometry(QtCore.QRect(290, 120, 291, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.pushButton_calculate_area.setFont(font)
        self.pushButton_calculate_area.setObjectName("pushButton_calculate_area")
        self.label_2 = QtWidgets.QLabel(ProjektInformatykaDialogBase)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 481, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton_clean = QtWidgets.QPushButton(ProjektInformatykaDialogBase)
        self.pushButton_clean.setGeometry(QtCore.QRect(10, 280, 271, 41))
        self.pushButton_clean.setObjectName("pushButton_clean")

        self.retranslateUi(ProjektInformatykaDialogBase)
        self.button_box.accepted.connect(ProjektInformatykaDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(ProjektInformatykaDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProjektInformatykaDialogBase)

    def retranslateUi(self, ProjektInformatykaDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ProjektInformatykaDialogBase.setWindowTitle(_translate("ProjektInformatykaDialogBase", "Projekt Informatyka"))
        self.label.setText(_translate("ProjektInformatykaDialogBase", "WYBIERZ WARSTWĘ:"))
        self.label_answer.setText(_translate("ProjektInformatykaDialogBase", "WYNIK:"))
        self.pushButton_calculate_dh.setText(_translate("ProjektInformatykaDialogBase", "OBLICZ PRZEWYŻSZENIE"))
        self.pushButton_calculate_area.setText(_translate("ProjektInformatykaDialogBase", "OBLICZ POLE POWIERZCHNI"))
        self.label_2.setText(_translate("ProjektInformatykaDialogBase", "WITAJ! CO MOGĘ DZIŚ DLA CIEBIE OBLICZYĆ? :)"))
        self.pushButton_clean.setText(_translate("ProjektInformatykaDialogBase", "Wyczyść konsolę wynikową"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjektInformatykaDialogBase = QtWidgets.QDialog()
    ui = Ui_ProjektInformatykaDialogBase()
    ui.setupUi(ProjektInformatykaDialogBase)
    ProjektInformatykaDialogBase.show()
    sys.exit(app.exec_())
